spring:
  application:
    name: CreditPipeline
  data:
    mongodb:
      host: localhost
      port: 27017
      database: credit
      username: admin
      password: admin
      authentication-database: admin
